version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: vybe-backend
    ports:
      - "4000:4000"
    env_file:
      - ./Server/.env
    # Restart automatically if it crashes
    restart: always

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: vybe-frontend
    ports:
      # Map host port 3000 to container port 80 (Nginx)
      # i can will access the app at http://localhost:3000
      - "3000:80"
    # The frontend shouldn't start until the backend is up
    depends_on:
      - backend
    restart: always
