apiVersion: apps/v1
kind: Deployment
metadata:
  name: vybe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vybe-frontend
  template:
    metadata:
      labels:
        app: vybe-frontend
    spec:
      containers:
      - name: frontend
        image: socialmediaplatformvybe-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
