apiVersion: v1
kind: Secret
metadata:
  name: vybe-secrets
type: Opaque
stringData:
  CLIENT_URL: "your-client-url-placeholder"
  MONGODB_URI: "your-mongodb-uri-placeholder"
  INNGEST_EVENT_KEY: "your-inngest-event-key-placeholder"
  INNGEST_SIGNING_KEY: "your-inngest-signing-key-placeholder"
  CLERK_PUBLISHABLE_KEY: "your-clerk-publishable-key-placeholder"
  CLERK_SECRET_KEY: "your-clerk-secret-key-placeholder"
  IMAGEKIT_PUBLIC_KEY: "your-imagekit-public-key-placeholder"
  IMAGEKIT_PRIVATE_KEY: "your-imagekit-private-key-placeholder"
  IMAGEKIT_URL_ENDPOINT: "your-imagekit-url-endpoint-placeholder"
  SENDER_EMAIL: "your-sender-email-placeholder"
  SMTP_USER: "your-smtp-user-placeholder"
  SMTP_PASS: "your-smtp-pass-placeholder"
